### ISSUE TITLE
BP-2546 Unable to complete the order with Bancontact configured without CSE

### ISSUE THREAD

**Issue by ennostuurman** [buckaroo-it/Magento2_Hyva#26]
When client side isn't enabled in the Magento backend:

[
![DD-889-client-side-yes-no](https://github.com/buckaroo-it/Magento2_Hyva/assets/1906257/a52c2e2f-8cad-4833-aab1-b92a8f21693d)
](url)

Bancontact will just show a 0 in the output.

![bucakroo-hyva-react-checkout-bancontact-not-clientside](https://github.com/buckaroo-it/Magento2_Hyva/assets/1906257/55c28e4c-2fd9-4ed3-854f-f2c65ef997a3)

When you try to place an order, client side validation executes and the response "One or more fields are required" shows up leaving the user with no clue what to do.

![buckaroo-bancontact-error-not-clientside](https://github.com/buckaroo-it/Magento2_Hyva/assets/1906257/af35269a-b46a-46ca-911b-9d4f7ce42acf)

When you enable client side configuration, Bancontact works as expected showing the CC input fields etc..

**Comment by Buckaroo-Rene** [comment]
@ennostuurman ,

Thank you for informing us about this issue. We'll look into it.

**Comment by ennostuurman** [comment]
@Buckaroo-Rens any update on this issue?

**Comment by Buckaroo-Rene** [comment]
Goodmorning @ennostuurman,

Sorry we did miss this ticket when updating.
The issue should be resolved in our latest release:
[v1.0.1](https://github.com/buckaroo-it/Magento2_Hyva/releases/tag/v1.0.1)

**Comment by ennostuurman** [comment]
Thanks @Buckaroo-Rene we're going to upgrade and test this out.
