### ISSUE TITLE
BP-2555 Losing session after redirect from Buckaroo test checkout

### ISSUE THREAD

**Issue by ennostuurman** [buckaroo-it/Magento2_Hyva#27]
**Prerequisites:**
Magento 2.4.5-p2
hyva-themes/magento2-react-checkout  1.1.2 
buckaroo/magento2        v1.44.0
buckaroo/magento2graphql 1.0.0
buckaroo/magento2_hyva 1.0.0

**Issue:** 
Customer session data are lost after redirect from https://testcheckout.buckaroo.nl/

**Steps to reproduce:**
- login as a customer on the Hyva React checkout page
- select a Buckaroo payment method
- place an order with the Buckaroo test environment enabled
- you are redirected to https://testcheckout.buckaroo.nl/
- select a status : success or reject

Expected result:
- customer is redirected to the shop and is still logged in

Actual result:
- customer is logged out

I suspect this is related to 
- https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/storefront/customers-get-logged-out-or-lose-cart-content-on-magento-storefront.html?lang=en
- also described here https://github.com/buckaroo-it/Magento2/issues/54

**Comment by Buckaroo-Rene** [comment]
@ennostuurman ,
Thank you for providing us the information regarding this issue.
I was able to reproduce this with your steps, so we will look for a solution.

**Comment by ennostuurman** [comment]
@Buckaroo-Rene this issue is currently happening on a production site. Do you have an update?  Thanks!

**Comment by harli91** [comment]
Hi @ennostuurman we've update the github GraphQL module with a pull request(to developer) with the fix for this

**Comment by ennostuurman** [comment]
@harli91 @Buckaroo-Rene thanks for the update, I don't mind to apply a composer patch on production until the change has been added to an upcoming updated release. But isn't this issue serious enough in terms of user experience and conversion (especially in case of rejected payments) to have it in an official minor / patch release asap?
